[package]
name = "chirp8-avr"
version = "0.1.0"
authors = ["Dr. ERDI Gergo <gergo@erdi.hu>"]
build-std = "core"

[build-dependencies]
cc = "1.0"

[dependencies]
chirp8-engine = { path = "chirp8-engine" }
avr-std-stub = { version = "1.0" }
